---
title: "NotebookLab4"
author: "Thomas Maria Frey"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

# imports

library(dplyr)
library(tidyr)
library(lmtest)

# functions

homocesdasticity_check <- function(lang_data, nonlinear_model, mdl,
                                   a_initial=0, b_initial=0,
                                   c_initial=0, d_initial=0) {
  print(sprintf("Model: %s", mdl))
  print(sprintf("a: %f, b: %f, c: %f, d: %f", a_initial, b_initial, c_initial, d_initial))
  
  residuals_nonlinear_model <- residuals(nonlinear_model)
  fitted_nonlinear_model    <- fitted(nonlinear_model)
  
  # Create a linear model for the squared residuals
  lm_resid <- lm(residuals_nonlinear_model^2 ~ fitted_nonlinear_model)
  
  # Perform the Breusch-Pagan test
  bp_test_result <- bptest(lm_resid)
  #print(bp_test_result)
  
  #TODO: Check if any is sensible here.
  
  # lower than 0.05 indicating the presence of heteroscedasticity, take aggregated values
  show_plot_1  <- FALSE
  show_plot_2  <- FALSE
  if(bp_test_result[4] < 0.05) {
    print("aggregate")
    if (agg_count <= 2) {
      show_plot_1  <- TRUE
      agg_count   <<- agg_count + 1
    }
    
    aggregation <- aggregate(lang_data, list(lang_data$N),mean)
    
    if (mdl == "1") {
      linear_model <- lm(log(K2) ~ log(N), aggregation)
      b_initial    <- coef(linear_model)[2]
      result_model <- nls(K2 ~ (N / 2)^b, data=aggregation,
                          start=list(b=b_initial), trace=TRUE)
    } else if (mdl == "2") {
      linear_model <- lm(log(K2) ~ log(N), aggregation)
      a_initial    <- exp(coef(linear_model)[1])
      b_initial    <- coef(linear_model)[2]
      result_model <- nls(K2 ~ a * N^b, data=aggregation,
                          start=list(a=a_initial, b=b_initial), trace=TRUE)
    } else if (mdl == "3") {
      linear_model <- lm(log(K2) ~ N, aggregation)
      a_initial    <- exp(coef(linear_model)[1])
      c_initial    <- coef(linear_model)[2]
      result_model <- nls(K2 ~ a * exp(c * N), data=aggregation,
                          start=list(a=a_initial, c=c_initial), trace=TRUE)
    } else if (mdl == "4") {
      linear_model <- lm(K2 ~ log(N), aggregation)
      a_initial    <- exp(coef(linear_model)[1])
      result_model <- nls(K2 ~ a * log(N), data=aggregation,
                          start=list(a=a_initial), trace=TRUE)
    } else if (mdl == "1+") {
      linear_model <- lm(log(K2) ~ log(N), aggregation)
      b_initial    <- coef(linear_model)[1]
      d_initial    <- 0
      result_model <- nls(K2 ~ (N / 2)^b + d, data=aggregation,
                          start=list(b=b_initial, d=d_initial), trace=TRUE)
    } else if (mdl == "4+") {
      linear_model <- lm(K2 ~ log(N), aggregation)
      a_initial    <- exp(coef(linear_model)[1])
      d_initial    <- 0
      result_model <- nls(K2 ~ a * log(N) + d, data=aggregation,
                          start=list(a=a_initial, d=d_initial), trace=TRUE)
    }
  } else {
    print("no aggregate")
    if (no_agg_count <= 2) {
      show_plot_2    <- TRUE
      no_agg_count  <<- no_agg_count + 1
    }
    
    result_model <- nonlinear_model
  }
  
  # plot data using old values
  # * in case of aggregation to be able to compare results with aggregation
  # * in case of no aggregation to confirm that aggregation was not needed
  if (show_plot_1 | show_plot_2) {
    plot(lang_data$N, lang_data$K2,
         main=sprintf("Model: %s, %s", mdl, if (show_plot_1) {"w/ agg"} else {"w/o agg"}))
    if (mdl == "1") { # f(n) = (n/2)^b
      b <- coef(nonlinear_model)["b"]
      lines(lang_data$N, (lang_data$N / 2)^b, type="l", col="red")
    } else if (mdl == "2") { # f(n) = an^b
      a <- coef(nonlinear_model)["a"]#2a
      b <- coef(nonlinear_model)["b"]#2b
      lines(lang_data$N, a * lang_data$N^b, type="l", col="red")
    } else if (mdl == "3") { # f(n) = ae^{cn}
      a <- coef(nonlinear_model)["a"]
      c <- coef(nonlinear_model)["c"]
      lines(lang_data$N, a * exp(c * lang_data$N), type="l", col="red")
    } else if (mdl == "4") { # f(n) = a*log(n)
      a <- coef(nonlinear_model)["a"]
      lines(lang_data$N, a * log(lang_data$N), type="l", col="red")
    } else if (mdl == "1+") { # f(n) = (n/2)^b
      b <- coef(nonlinear_model)["b"]
      d <- coef(nonlinear_model)["d"]
      lines(lang_data$N, (lang_data$N / 2)^b + d, type="l", col="red")
    } else if (mdl == "4+") { # f(n) = a*log(n)+d
      a <- coef(nonlinear_model)["a"]
      d <- coef(nonlinear_model)["d"]
      lines(lang_data$N, a * log(lang_data$N) + d, type="l", col="red")
    }
  }

  # plot data using new values (with aggregation)
  if (show_plot_1) {
    plot(aggregation$N, aggregation$K2,
         main=sprintf("Model: %s, %s", mdl, "w/ agg"))
    if (mdl == "1") { # f(n) = (n/2)^b
      b <- coef(result_model)["b"]
      lines(aggregation$N, (aggregation$N / 2)^b, type="l", col="red")
    } else if (mdl == "2") { # f(n) = an^b
      a <- coef(result_model)["a"]#2a
      b <- coef(result_model)["b"]#2b
      lines(aggregation$N, a * aggregation$N^b, type="l", col="red")
    } else if (mdl == "3") { # f(n) = ae^{cn}
      a <- coef(result_model)["a"]
      c <- coef(result_model)["c"]
      lines(aggregation$N, a * exp(c * aggregation$N), type="l", col="red")
    } else if (mdl == "4") { # f(n) = a*log(n)
      a <- coef(result_model)["a"]
      lines(aggregation$N, a * log(aggregation$N), type="l", col="red")
    } else if (mdl == "1+") { # f(n) = (n/2)^b
      b <- coef(result_model)["b"]
      d <- coef(result_model)["d"]
      lines(aggregation$N, (aggregation$N / 2)^b + d, type="l", col="red")
    } else if (mdl == "4+") { # f(n) = a*log(n)+d
      a <- coef(result_model)["a"]
      d <- coef(result_model)["d"]
      lines(aggregation$N, a * log(aggregation$N) + d, type="l", col="red")
    }
  }
  
  return(result_model)
}

# create empty table for overview data of each language 
data_overview <- data.frame(Language=character(),
                            n=integer(),
                            mu_n=double(),
                            sigma_n=double(),
                            mu_x=double(),
                            sigma_x=double(),
                            stringsAsFactors=FALSE)

column_names           <- c("Languages", "0", "1", "2", "3",
                            "4", "1+", "2+", "3+", "4+")
column_parameter_names <- c("Languages", "1b", "2a", "2b", "3a",
                            "3c", "4a", "1+b", "1+d", "2+a", "2+b",
                            "2+d", "3+a", "3+c", "3+d", "4+a", "4+d")

# s table
residualStandardErrorTable <- data.frame(matrix(ncol = 10, nrow = 0))
names(residualStandardErrorTable) <- column_names

# AIC table
akaikeInformationCriterionTable<- data.frame(matrix(ncol = 10, nrow = 0))
names(akaikeInformationCriterionTable) <- column_names

# AIC delta table
aicdifferenceTable<- data.frame(matrix(ncol = 10, nrow = 0))
names(aicdifferenceTable) <- column_names

# column parameter table
columnparametertable<- data.frame(matrix(ncol = 17, nrow = 0))
names(columnparametertable) <- column_parameter_names

# main

agg_count    <- 1
no_agg_count <- 1

main <- function(lang, filename, index) {
  # SECTION: load data
  lang_data            <- data.frame(read.table(filename, header=FALSE, quote=""))
  colnames(lang_data)  <- c("N", "K2", "D")
  lang_data            <- lang_data[order(lang_data$N), ]
  
  # validate if data meets the requirements
  lang_data$Validation <- (4 - 6 / lang_data$N <= lang_data$K2) &
                          (lang_data$K2 <= (lang_data$N - 1))
  #print(head(lang_data))
  print(lang)
  print(table(lang_data$Validation))
  
  # calculate overview data
  n        <- length(lang_data$N)
  mu_n     <- mean(lang_data$N)
  sigma_n  <- sum((lang_data$N  - mu_n) ** 2) / n
  mu_k2    <- mean(lang_data$K2)
  sigma_k2 <- sum((lang_data$K2 - mu_n) ** 2) / n
  # add to table
  data_overview[nrow(data_overview) + 1,] <<- list(lang,
                                                   n,
                                                   mu_n,
                                                   sigma_n,
                                                   mu_k2,
                                                   sigma_k2)
  
  # thomas code here
  RSSVector       <- numeric(10)
  AICVector       <- numeric(10)
  AICDeltaVector  <- numeric(10)
  ParameterVector <- numeric(17)
  
  RSSVector[1]       <- lang
  AICVector[1]       <- lang
  AICDeltaVector[1]  <- lang
  ParameterVector[1] <- lang
  
  #Null Model TODO
  # f(n) = (1 - 1 / N) * (5 - 6 / N)
  RSS                <- sum((lang_data$K2 - (1 - 1 / lang_data$N) * (5 - 6 / lang_data$N))^2)
  p                  <- 0
  RSSVector[2]       <- sqrt(RSS / (n - p))
  AICVector[2]       <- n * log(2 * pi) + n * log(RSS / n) + n + 2 * (p + 1)
  AICDeltaVector[2]  <- "-"
  
  # General steps:
  # 1. Calculate sensible starting values
  # 2. Calculate an initial non linear regression model 
  # 3. Check for homocesdasticity, if no take precautions
  # 4. Calculate optimal parameters and values
  
  #Calculating Model 1 => MANDATORY
  #1
  linear_model <- lm(log(K2)~log(N), lang_data)
  b_initial    <- coef(linear_model)[2]
  #2 f(n) = (n/2)^b
  nonlinear_model <- nls(K2 ~ (N / 2)^b, data=lang_data,
                         start=list(b=b_initial), trace = TRUE)
  #3 
  nonlinear_model <- homocesdasticity_check(lang_data, nonlinear_model, "1",
                                            b_initial=b_initial)
  #4
  RSSVector[3]       <- sqrt(deviance(nonlinear_model) / df.residual(nonlinear_model))#s
  AICVector[3]       <- AIC(nonlinear_model)
  AICDeltaVector[3]  <- "-"
  ParameterVector[2] <- coef(nonlinear_model)["b"]#1b
  
  #Calculating Model 2 => MANDATORY
  #1
  linear_model <- lm(log(K2) ~ log(N), lang_data)
  a_initial    <- exp(coef(linear_model)[1])
  b_initial    <- coef(linear_model)[2]
  #2 f(n) = an^b
  nonlinear_model <- nls(K2 ~ a * N^b, data=lang_data,
                         start=list(a=a_initial, b=b_initial), trace = TRUE)
  #3
  nonlinear_model <- homocesdasticity_check(lang_data, nonlinear_model, "2",
                                            a_initial=a_initial, b_initial=b_initial)
  #4
  AICVector[4]       <- AIC(nonlinear_model)#AIC
  RSSVector[4]       <- sqrt(deviance(nonlinear_model) / df.residual(nonlinear_model))#s
  AICDeltaVector[4]  <- "-"#TODO
  ParameterVector[3] <- coef(nonlinear_model)["a"]#2a
  ParameterVector[4] <- coef(nonlinear_model)["b"]#2b
  
  #Calculating Model 3 => MANDATORY
  #1
  linear_model <- lm(log(K2) ~ N, lang_data)
  a_initial    <- exp(coef(linear_model)[1])
  c_initial    <- coef(linear_model)[2]
  #2 f(n) = ae^{cn}
  nonlinear_model <- nls(K2 ~ a * exp(c * N), data=lang_data,
                         start=list(a=a_initial, c=c_initial), trace = TRUE)
  #3
  nonlinear_model <- homocesdasticity_check(lang_data, nonlinear_model, "3",
                                            a_initial=a_initial, c_initial=c_initial)
  
  RSSVector[5]       <- sqrt(deviance(nonlinear_model) / df.residual(nonlinear_model))#s
  AICVector[5]       <- AIC(nonlinear_model)#AIC
  AICDeltaVector[5]  <- "-"#TODO
  ParameterVector[5] <- coef(nonlinear_model)["a"]#3a
  ParameterVector[6] <- coef(nonlinear_model)["c"]#3c
  
  #Calculating Model 4 => NEW
  #1
  linear_model <- lm(K2 ~ log(N), lang_data)
  a_initial    <- exp(coef(linear_model)[1])
  #2 f(n) = a*log(n)
  nonlinear_model <- nls(K2 ~ a * log(N), data=lang_data,
                         start=list(a=a_initial), trace=TRUE)
  #3 
  nonlinear_model <- homocesdasticity_check(lang_data, nonlinear_model, "4",
                                            a_initial=a_initial)
  #4
  RSSVector[6]       <- sqrt(deviance(nonlinear_model) / df.residual(nonlinear_model))#s
  AICVector[6]       <- AIC(nonlinear_model)#AIC
  AICDeltaVector[6]  <- "-"
  ParameterVector[7] <- coef(nonlinear_model)["a"]#4a
  
  #Calculating Model 1+ => MANDATORY
  #1
  linear_model <- lm(log(K2) ~ log(N), lang_data)
  b_initial    <- coef(linear_model)[2]
  d_initial    <- 0 #idk what to put here tbh tbh
  #2 f(n) = (n/2)^b
  nonlinear_model <- nls(K2 ~ (N / 2)^b + d, data=lang_data,
                         start=list(b=b_initial, d=d_initial), trace=TRUE)
  #3 
  nonlinear_model <- homocesdasticity_check(lang_data, nonlinear_model, "1+",
                                            b_initial=b_initial, d_initial=d_initial)
  #4
  RSSVector[7]       <- sqrt(deviance(nonlinear_model) / df.residual(nonlinear_model))#s
  AICVector[7]       <- AIC(nonlinear_model)#AIC
  AICDeltaVector[7]  <- "-"
  ParameterVector[8] <- coef(nonlinear_model)["b"]#1+b
  ParameterVector[9] <- coef(nonlinear_model)["d"]#1+d
  
  #Calculating Model 2+ => ADVANCED
  RSSVector[8]        <- "-"
  AICVector[8]        <- "-"
  AICDeltaVector[8]   <- "-"
  ParameterVector[10] <- "-"#2+a
  ParameterVector[11] <- "-"#2+b
  ParameterVector[12] <- "-"#2+d
  
  #Calculating Model 3+ => ADVANCED
  RSSVector[9]        <- "-"
  AICVector[9]        <- "-"
  AICDeltaVector[9]   <- "-"
  ParameterVector[13] <- "-"#3+a
  ParameterVector[14] <- "-"#3+b
  ParameterVector[15] <- "-"#3+d
  
  #Calculating Model 4+ => NEW
  #1
  linear_model <- lm(K2 ~ log(N), lang_data)
  a_initial    <- exp(coef(linear_model)[1])
  d_initial    <- 0
  #2 f(n) = a*log(n)+d
  nonlinear_model <- nls(K2 ~ a * log(N) + d, data=lang_data,
                         start=list(a=a_initial, d=d_initial), trace=TRUE)
  #3 
  nonlinear_model <- homocesdasticity_check(lang_data, nonlinear_model, "4+",
                                            a_initial=a_initial, d_initial=d_initial)
  #4
  RSSVector[10]       <- sqrt(deviance(nonlinear_model) / df.residual(nonlinear_model))#s
  AICVector[10]       <- AIC(nonlinear_model)#AIC
  AICDeltaVector[10]  <- "-"
  ParameterVector[16] <- coef(nonlinear_model)["a"]#4+a
  ParameterVector[17] <- coef(nonlinear_model)["d"]#4+d
  
  AIC_best <- min(na.omit(as.numeric(AICVector)))
  print(sprintf("AIC best: %f", AIC_best))
  for (i in 2:length(AICVector)) {
    AICDeltaVector[i] <- as.numeric(AICVector[i]) - AIC_best
  }

  akaikeInformationCriterionTable[index,] <<- AICVector
  columnparametertable[index,]            <<- ParameterVector
  residualStandardErrorTable[index,]      <<- RSSVector
  aicdifferenceTable[index,]              <<- AICDeltaVector
}

source = read.table("./list.txt", 
         header = TRUE,
         as.is = c("language","file")
        )

for (i in 1:nrow(source)) {
  main(source$language[i], source$file[i], i) # check your path
  if (i >= 100) {
    break
  }
}

# Print Tables
data_overview
residualStandardErrorTable
akaikeInformationCriterionTable
aicdifferenceTable
columnparametertable
```



```{r}
#1
png("31plots/vertices_meandependencylengths.png")

plot(Catalan$vertices, Catalan$mean_length,
       xlab = "vertices", ylab = "mean dependency length")

dev.off()

#2
png("31plots/logvertices_logmeandependencylengths.png")

plot(log(Catalan$vertices), log(Catalan$mean_length),
       xlab = "log(vertices)", ylab = "log(mean dependency length)")

dev.off()

#3
mean_Catalan = aggregate(Catalan, list(Catalan$vertices), mean)

#4
png("31plots/vertices_meanmeandependencylength.png")

plot(mean_Catalan$vertices, mean_Catalan$mean_length,
       xlab = "vertices", ylab = "mean mean dependency length")

dev.off()

#5
png("31plots/logvertices_logmeanmeandependencylength.png")

plot(log(mean_Catalan$vertices), log(mean_Catalan$mean_length),
       xlab = "log(vertices)", ylab = "log(mean mean dependency length)")

dev.off()

#6
png("31plots/vertices_meanmeandependencylength_greenred.png")

plot(log(Catalan$vertices), log(Catalan$mean_length),
       xlab = "vertices", ylab = "mean dependency length")
lines(log(mean_Catalan$vertices),log(mean_Catalan$mean_length), col = "green")
lines(log(mean_Catalan$vertices),log((mean_Catalan$vertices+1)/3), col = "red")

dev.off()

#7

png("31plots/vertices_degree2ndmoment_greenredblue.png")

plot(Catalan$vertices, Catalan$degree_2nd_moment,
       xlab = "vertices", ylab = "degree 2nd moment")
lines(mean_Catalan$vertices,mean_Catalan$degree_2nd_moment, col = "green")
lines(Catalan$vertices,
       (1 - 1/Catalan$vertices)*(5 - 6/Catalan$vertices), col = "red")
lines(Catalan$vertices,4-6/Catalan$vertices, col = "blue")
lines(Catalan$vertices,Catalan$vertices-1, col = "blue")

dev.off()
```




